name: Build
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Build for amd64
        run: go build -o hlscheck -v .
        env:
          GOOS: linux
          GOARCH: amd64
      - name: Archive amd64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: hlscheck-amd64
          path: hlscheck
      - name: Build for arm64
        run: go build -o hlscheck -v .
        env:
          GOOS: linux
          GOARCH: arm64
      - name: Archive arm64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: hlscheck-arm64
          path: hlscheck
